/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/article/index.vue')['default']
    Banner: typeof import('./src/components/banner/index.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Image: typeof import('./src/components/image/index.vue')['default']
    Message: typeof import('./src/components/message/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/swiper/index.vue')['default']
  }
}
